{{- if and .Values.secrets.create .Values.secrets.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carillon.fullname" . }}-secrets
  labels:
    {{- include "carillon.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.files }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
