{{- if and .Values.valkey.enabled .Values.valkey.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "carillon.valkeyFullname" . }}
  labels:
    {{- include "carillon.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.valkey.persistence.storageClass }}
  storageClassName: {{ .Values.valkey.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.valkey.persistence.size | quote }}
{{- end }}
